title: The Residual Stream
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Refining my knowledge bit by bit
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://guy-dar.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: guy_dar1
github_username:  guy-dar

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-scholar

scholar:
  style: modern-language-association

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
